@startuml ej2
skinparam Monochrome true
skinparam classAttributeIconSize 0

class Mensajero{
 +enviar(mensaje: String)
}
class Conexion{
 +enviar(mensaje:  string)
}
Mensajero -r-> Conexion : conexion

class ConexionSegura{
 +enviar(mensaje: String)
 +setEncriptador(e: Encriptador)
}
Conexion <|-r- ConexionSegura

note "Strategy" as N1
interface Encriptador{
 +encriptar(mensaje: String): String
}
N1 .right. Encriptador
ConexionSegura -down-> Encriptador : encriptador

class RSA{
 +encriptar(mensaje: String): String
}
class RC4{
 +encriptar(mensaje: String): String
}
class Blowfish{
 +encriptar(mensaje: String): String
}

Encriptador <|.. RSA
Encriptador <|.. RC4
Encriptador <|.. Blowfish
@enduml