@startuml ej1
skinparam ClassBackgroundColor transparent
skinparam NoteBackgroundColor transparent
skinparam classAttributeIconSize 0 
skinparam ClassBorderThickness 1.3
skinparam ClassBorderColor Black
skinparam NoteBorderColor Black
skinparam ArrowColor Black
skinparam shadowing false

class Archivo{
    +<<create>> Archivo(nombre: String, fecha: LocalDate, tamano:int)
}

class Directorio{
    +<<create>> Directorio(nombre: String, fecha: LocalDate)
}

abstract class FileSystem{
    -nombre: String
    -fechaCreacion: LocalDate
    -tamano: int
    +<<create>> FileSystem(nombre: String, fecha: LocalDate, tamano:int)
    +tamanoTotalOcupado(): int
    +{abstract} archivoMasGrande(): Archivo
    +{abstract} archivoMasNuevo(): Archivo
}
skinparam linetype ortho
FileSystem <|-u- Archivo
FileSystem <|-- Directorio

Directorio "1" o--> "*" FileSystem

@enduml